"""Generate docs/rules.md from src/rules.py plus fixture coverage (how many fixtures fire each rule).

  python scripts/gen_rules_doc.py            # write docs/rules.md
  python scripts/gen_rules_doc.py --check    # exit 1 if docs/rules.md is stale
"""
import argparse
import glob
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.adapters import parse_canonical_json  # noqa: E402
from src.html_to_json import parse_html  # noqa: E402
from src.linter_renderer import lint  # noqa: E402
from src.rules import RULES, RULESET_VERSION, rule_id_from_ref  # noqa: E402

OUT = ROOT / "docs" / "rules.md"


def coverage():
    """Per rule: number of fixture files on which the check fires (fail) and appears at all, under either profile."""
    fires, appears, unregistered = Counter(), Counter(), Counter()
    paths = set(glob.glob(str(ROOT / "examples" / "**" / "*.html"), recursive=True))
    paths |= set(glob.glob(str(ROOT / "examples" / "coverage" / "*.json")))
    for path in sorted(paths):
        text = Path(path).read_text(encoding="utf-8")
        instance = parse_canonical_json(text) if path.endswith(".json") else parse_html(text)
        seen_fire, seen_any = set(), set()
        for profile in ("default", "strict_law"):
            for item in lint(instance, profile=profile)["checklist"]:
                rid = rule_id_from_ref(item.get("reference"))
                if rid is None:
                    unregistered[item.get("reference")] += 1
                    continue
                seen_any.add(rid)
                if item["status"] == "fail":
                    seen_fire.add(rid)
        fires.update(seen_fire); appears.update(seen_any)
    return fires, appears, unregistered


def render():
    fires, appears, unregistered = coverage()
    by_domain = defaultdict(list)
    for r in RULES.values():
        by_domain[r.domain].append(r)
    lines = [
        "# Layer 1 rule registry",
        "",
        f"Ruleset version **{RULESET_VERSION}** · {len(RULES)} rules · generated by `scripts/gen_rules_doc.py` from `src/rules.py` (do not edit by hand).",
        "",
        "Rule ids are the linter's long-standing `reference` values with the per-experiment suffix (`:exp-N`) stripped; "
        "they appear on every checklist item as `rule_id`, in the UI detail panel and in the printed report. "
        "Each item also carries the registry's `rule_title` and `rule_kind` (null only for an unregistered reference) so the UI can frame a finding without a second lookup. "
        "`kind` follows the linter's severity classes (structural / law_critical / advisory; `required` is the missing-field family). "
        "`jurisdiction` is a first-pass tag for Phase 3.2 — **IL-form** = specific to the Israeli Council request form or Israeli law, "
        "**generic** = welfare/science checks any jurisdiction would keep; the maintainer should review these tags before they drive a pack split. "
        "`fixtures` = number of example files (every HTML file under `examples/` plus the synthetic canonical-JSON fixtures in `examples/coverage/`, both profiles) on which the rule fires / appears at all.",
        "",
        "Versioning: `RULESET_VERSION` (in `src/rules.py`) is bumped whenever a rule is added, removed, or its trigger changes, "
        "so a report's `ruleset_version` says which rules it was reviewed under.",
        "",
    ]
    for domain in sorted(by_domain):
        lines += [f"## {domain}", "", "| rule id | kind | jurisdiction | title | fixtures (fire / appear) |", "|---|---|---|---|---|"]
        for r in sorted(by_domain[domain], key=lambda x: x.id):
            lines.append(f"| `{r.id}` | {r.kind} | {r.jurisdiction} | {r.title} | {fires.get(r.id, 0)} / {appears.get(r.id, 0)} |")
        lines.append("")
    never = sorted(r.id for r in RULES.values() if appears.get(r.id, 0) == 0)
    lines += ["## Coverage gaps", "",
              f"{len(never)} rules never appear on any fixture (they only emit a checklist item when they fire, and no fixture trips them): "
              + ", ".join(f"`{i}`" for i in never) + ".", "",
              "Rules that cannot be reached from canonical JSON (the schema rejects the instance before the linter runs) are documented in `examples/coverage/README.md`.", "",
              "Unregistered references seen on fixtures: " + (", ".join(f"`{k}`" for k in sorted(unregistered)) if unregistered else "none") + ".", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit("docs/rules.md is stale — run scripts/gen_rules_doc.py")
        print("docs/rules.md up to date")
    else:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)}")
