"""Generate docs/schema.md — the canonical protocol JSON contract — from src/schema.py,
plus a conformance section measuring how the reference HTML adapter's output actually
compares to the schema over the fixture tree.

  python scripts/gen_schema_doc.py            # write docs/schema.md
  python scripts/gen_schema_doc.py --check    # exit 1 if stale
"""
import argparse
import glob
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.adapters import _validator  # noqa: E402
from src.html_to_json import parse_html  # noqa: E402
from src.schema import IACUC_SCHEMA_V2 as S  # noqa: E402

OUT = ROOT / "docs" / "schema.md"


def _walk(node, path, required, rows):
    t = node.get("type", "")
    meta = node.get("x_meta") or {}
    if path:
        rows.append({
            "path": path, "type": t if isinstance(t, str) else "/".join(t), "required": required,
            "title": meta.get("title", ""), "description": meta.get("description") or node.get("description", ""),
            "expected": meta.get("expected", ""), "enum": node.get("enum"), "examples": meta.get("examples") or node.get("examples"),
            "rules": meta.get("rules") or [],
        })
    if t == "object" or "properties" in node:
        req = set(node.get("required", []))
        for k, v in (node.get("properties") or {}).items():
            _walk(v, f"{path}.{k}" if path else k, k in req, rows)
    if t == "array" and isinstance(node.get("items"), dict):
        _walk(node["items"], f"{path}[]", False, rows)


def conformance():
    counts = Counter()
    n = clean = 0
    for f in sorted(set(glob.glob(str(ROOT / "examples" / "**" / "*.html"), recursive=True))):
        n += 1
        errs = list(_validator.iter_errors(parse_html(Path(f).read_text(encoding="utf-8"))))
        clean += not errs
        for e in errs:
            path = ".".join("[]" if isinstance(p, int) else str(p) for p in e.absolute_path)
            path = path.replace(".[]", "[]")
            detail = e.message if e.validator == "required" else f"{e.validator} — actual values are outside {e.validator_value!r}"[:140]
            counts[(path, detail)] += 1
    return n, clean, counts


def render():
    rows = []
    _walk(S, "", False, rows)
    lines = [
        "# Canonical protocol schema — the integration contract",
        "",
        f"`{S.get('$id', '')}` · JSON Schema draft-07 · generated by `scripts/gen_schema_doc.py` from `src/schema.py` (do not edit by hand).",
        "",
        "This JSON object is what every ingest adapter produces and what the deterministic linter and the LLM layers consume. "
        "An institution with a different protocol system writes an adapter that emits this shape (see `docs/adapters.md`); "
        "it never has to read the HTML parser. Send it as a `.json` upload or as `{\"instance\": {...}}` to `/api/analyze`; "
        "it is validated strictly against this schema on the way in.",
        "",
        f"Top-level required blocks: {', '.join(f'`{r}`' for r in S.get('required', []))}.",
        "",
        "## Fields",
        "",
        "| path | type | req | meaning | allowed / expected | examples |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        allowed = ("`" + "` · `".join(map(str, r["enum"])) + "`") if r["enum"] else (r["expected"] or "")
        ex = ", ".join(f"`{e}`" for e in (r["examples"] or [])[:3]) if r["examples"] else ""
        meaning = (r["title"] + (" — " if r["title"] and r["description"] else "") + r["description"]).replace("|", "\\|")
        lines.append(f"| `{r['path']}` | {r['type']} | {'yes' if r['required'] else ''} | {meaning} | {allowed.replace('|', '\\|')} | {ex} |")
    rules = [(r["path"], rule) for r in rows for rule in r["rules"]]
    if rules:
        lines += ["", "## Field rules (from `x_meta.rules`)", ""]
        lines += [f"- `{p}`: {rule}" for p, rule in rules]
    n, clean, counts = conformance()
    lines += ["", "## Conformance of the reference adapter (measured)", "",
              f"`il-council-html` output validated against this schema over {n} fixture files: **{clean} validate clean**, "
              f"{sum(counts.values())} violations in {len(counts)} distinct (path, rule) classes. The linter is written against "
              "what the parser actually emits, so these are documentation debt, not review errors — but a third-party adapter that "
              "follows the schema literally will emit *different* values (e.g. English enums) than the reference adapter does. "
              "Resolving this (normalize in the parser, or widen the schema to the bilingual reality) is a behaviour change for the "
              "maintainer to decide; until then, adapter authors should copy the reference adapter's vocabularies where they differ:", ""]
    for (path, detail), c in counts.most_common(25):
        lines.append(f"- `{path}` ({c} occurrences): {detail}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit("docs/schema.md is stale — run scripts/gen_schema_doc.py")
        print("docs/schema.md up to date")
    else:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
